SHELL =	sh.exe
TARGET       = DigitalPotControl
BOARD_TAG    = uno_pic32
SERIAL_PORT = com1
MPIDE_DIR=C:/mpide
ARDUINO_PREFERENCES_PATH=C:/Users/??????/AppData/Roaming/mpide/preferences.txt
ARDUINO_LIBS = SPI
include $(MPIDE_DIR)/chipKIT.mk
CORE_INCLUDE_NAME = 
RESET_SERIAL = ResetSerial.exe
